# Generated by Django 4.1.7 on 2023-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.CharField(default='', max_length=100),
        ),
    ]
